### ISSUE TITLE
Include top_languages in stats

### ISSUE THREAD

**Issue by bzg** [etalab/data-codes-sources-fr#41]
In a similar way than we expose stats about the licenses. 

This may be a bit more complex because there may be more than one language for each repository. We could decide to pick up only one language per repository.

WDYT?

PS: mentioned in [this issue](https://github.com/etalab/codegouvfr/issues/59).

**Comment by AntoineAugusti** [comment]
I've done this in the mentioned commit.

Unfortunately languages are not well detected.
- For GitHub, [the API](https://developer.github.com/v3/repos/#parameters-2) lists a single language (the recognised major one in the repository) when listing repos of an org. To get a detailed list of detected languages / repo, we need [to use a different endpoint](https://developer.github.com/v3/repos/#list-languages). This would require a great number of API calls to get. We would also have an array instead of a string for the `langage` field.
- GitLab does not provide information about languages when listing repositories of an org. We need to call [a dedicated endpoint per repo](https://docs.gitlab.com/ee/api/projects.html#languages) as well.

**Comment by bzg** [comment]
PS: You can close the issue for now, I referenced [here](https://github.com/etalab/codegouvfr/issues/59) if we need to reopen it. Thanks again!

**Comment by AntoineAugusti** [comment]
Another possibility would be to use a GitHub / GitLab database and to query our list of orgs.
