### ISSUE TITLE
gitlabjf.ccomptes.fr not harvested?

### ISSUE THREAD

**Issue by bzg** [etalab/data-codes-sources-fr#42]
https://github.com/etalab/data-codes-sources-fr/commit/036547f4bfcd4caad4ebd5cbe65d08a5d699aa18 adds a new forge but I cannot see any of the public groups/repositories from this forge. Did I forget to commit information about it?

**Comment by AntoineAugusti** [comment]
Will be fixed by https://github.com/DISIC/politique-de-contribution-open-source/pull/185.

The code to detect if a platform is a "bare platform" and should be scrapped entirely https://github.com/etalab/data-codes-sources-fr/blob/afa489727fc2232b6b0d9618250e808354b1ebfb/platforms.py#L52-L60 doesn't account for when a GitLab instance is listed with its `/explore/groups` URL.

**Comment by AntoineAugusti** [comment]
@bzg Feel free to close this issue once the next data collection jobs kicks in (and hopefully fetch the repositories as expected).

**Comment by bzg** [comment]
`gitlabjf.ccomptes.fr` is now correctly harvested, closing this issue.
