### ISSUE TITLE
gitlab.inria.fr groups don't display any repository

### ISSUE THREAD

**Issue by neurolit** [etalab/data-codes-sources-fr#43]
Hi!

We can't list any repository when displaying a gitlab.inria.fr group  in https://code.etalab.gouv.fr, whereas these respositories are listed on the homepage.

For example, [Grid5000 search link in code.etalab](https://code.etalab.gouv.fr/fr/repos?g=https%3A%2F%2Fgitlab.inria.fr%2Fgroups%2Fgrid5000) shows no respository. There should be 17 of them.

**Comment by bzg** [comment]
Thanks for reporting this! Fixed now in production.

The issue was on [the frontend](https://github.com/etalab/codegouvfr), not in this repository.

For GitLab instances, `https://[gitlab-instance]/groups/[group]` redirects to `https://[gitlab-instance]/[group]`, so it's fine to use `https://[gitlab-instance]/groups/[group]` as the URL of the group in [code.etalab.gouv.fr](https://code.etalab.gouv.fr/en/groups).

But on [the repos list of code.etalab.gouv.fr](https://code.etalab.gouv.fr/en/repos), the search for all repos of a group means searching for all `https://[forge]/[group]/*`, so I had to construct the correct group URL when this URL is used as a group filter.

Feel free to reopen this issue if it is not fixed on your side.
