### ISSUE TITLE
chande API key libraries.io

### ISSUE THREAD

**Issue by guillim** [etalab/data-codes-sources-fr#59]
it's a personnal one at the moment

**Comment by bzg** [comment]
I've replaced the key with mine.  `libraries.io` only allows to create an account using GitHub, GitLab or Bitbucket, which prevents creating an `Etalab` account, since there is no such thing as an "Etalab" user.  At least you won't have to worry about Etalab relying on your API key - I'll watch this to see if we can set up something better.
